version: 2

sources:
  - name: raw_adventure_works
    database: fea24_11
    schema: raw_adventure_works
    tables:
      - name: customer
        description: "Tabela de clientes"
        columns:
          - name: customerid
            description: "Identificador único do cliente"
            tests:
              - not_null
          - name: territoryid
            description: "Identificador do território onde o cliente se localiza"
            tests:
              - not_null
              - relationships:
                  field: territoryid
                  to: source('raw_adventure_works', 'salesterritory')
          - name: modifieddate
            description: "Data do último registro"
            tests:
              - not_null

      - name: salesorderheader
        description: "Cabeçalho de pedidos de venda"
        columns:
          - name: salesorderid
            description: "Identificador de pedido de venda"
            tests:
              - unique
              - not_null
          - name: orderdate
            description: "Data de pedido de venda"
            tests:
              - not_null
          - name: duedate
            description: "Data de prazo de pedido"
            tests:
              - not_null
          - name: shipdate
            description: "Data de envio do pedido"
            tests:
              - not_null
          - name: status
            description: "Status do pedido"
            tests:
              - not_null
          - name: onlineorderflag
            description: "Identificador de pedidos feitos online"
            tests:
              - not_null
          - name: purchaseordernumber
            description: "Identificador de pedido de compra"
            tests:
              - unique
          - name: accountnumber
            description: "Número da conta do cliente"
            tests:
              - not_null
          - name: customerid
            description: "Identificador do cliente"
            tests:
              - not_null
              - relationships:
                  field: customerid
                  to: source('raw_adventure_works', 'customer')
          - name: salespersonid
            description: "Identificador do vendedor"
          - name: territoryid
            description: "identificador do território da compra"
            tests:
              - not_null
              - relationships:
                  field: territoryid
                  to: source('raw_adventure_works', 'salesterritory')
          - name: billtoaddressid
            description: "Identificador de endereço de cobrança"
            tests:
              - not_null
              - relationships:
                  field: addressid
                  to: source('raw_adventure_works', 'address')
          - name: shiptoaddressid
            description: "Identificador de endereço de envio"
          - name: shipmethodid
            description: "Identificador de método de envio"
            tests:
              - not_null
          - name: creditcardid
            description: "Identificador de cartão de crédito utilizado"
            tests:
              - relationships:
                  field: creditcardid
                  to: source('raw_adventure_works', 'creditcard')
          - name: creditcardapprovalcode
            description: "Código de aprovação de cartão de crédito"
            tests:
              - unique
          - name: currencyrateid
            description: "Identificador de taxa"
          - name: taxamt
            description: "Taxa mínima"
            tests:
              - not_null
          - name: freight
            description: "Taxa de frete"
            tests:
              - not_null
          - name: totaldue
            description: "Total devido"
            tests:
              - not_null
          - name: rollguide
            description: "Guide de linha"
          - name: modifieddate
            description: "Data da última modificação"
            tests:
              - not_null
      - name: salesreason
        columns:
          - name: salesreasonid
            description: "Identificador de motivo de venda"
            tests:
              - unique
              - not_null
          - name: name
            description: "Nome do motivo de venda"
            tests:
              - not_null
          - name: reasontype
            description: "Tipo de razão"
            tests:
              - not_null
          - name: modifieddate
            description: "Data da última modificação"
            tests:
              - not_null
      - name: creditcard
        columns:
          - name: creditcardid
            description: "Identificador de cartão de crédito"
            tests:
              - unique
              - not_null
          - name: cardtype
            description: "Tipo de cartão"
            tests:
              - not_null
          - name: cardnumber
            description: "Número do cartão de crédito"
            tests:
              - unique
              - not_null
      - name: product
        columns:
          - name: productid
            description: "Identificador de produto"
            tests:
              - not_null
          - name: productname
            description: "Nome do produto"
          - name: productnumber
            description: número do produto
            tests:
              - not_null
          - name: color
            description: "Cor do produto"
          - name: modifieddate
            description: "Data da última modificação"
            tests:
              - not_null
      - name: productcosthistory
        columns:
          - name: productid
            description: "Identificador do produto"
            tests:
              - not_null
              - relationships:
                  to: source('raw_adventure_works', 'product')
                  field: productid
          - name: startdate
            description: "Data de início do registro"
            tests:
              - not_null
          - name: enddate
            description: "Data fim do registro"
          - name: standardcost
            description: "Custo padrão do período"
            tests:
              - not_null
          - name: modifieddate
            description: "Data de último registro"
            tests:
              - not_null
      - name: salesterritory
        columns:
          - name: territoryid
            description: "Identificador do território da compra"
            tests:
              - unique
              - not_null
          - name: countryregioncode
            description: "Identificador da região do país"
            tests:
              - not_null
          - name: salesytd
            description: "Total de compras feitas de um ano para a data atual"
            tests:
              - not_null
          - name: saleslastyear
            description: "Compras feitas no último ano"
            tests:
              - not_null
          - name: modifieddate
            description: "Data da última modificação"
            tests:
              - not_null
      - name: salesorderdetail
        columns:
          - name: salesorderid
            description: "Identificador de pedido de venda"
            tests:
              - not_null
          - name: salesorderdetailid
            description: "Identificador de detalhamento de pedido de venda"
            tests:
              - unique
              - not_null
          - name: carriertrackingnumber
            description: "Número de rastreamendo da transportadora"
          - name: orderqty
            description: "Quantidade comprada"
            tests:
              - not_null
          - name: unitprice
            description: "Preço unitário"
            tests:
              - not_null
          - name: modifieddate
            description: "Data da última modificação do registro"
            tests:
              - not_null
          - name: productid
            description: "Identificador do produto"
            tests:
              - not_null
              - relationships:
                  field: productid
                  to: source('raw_adventure_works', 'product')
          - name: specialofferid
            description: "Identificador de oferta"
            tests:
              - not_null
      - name: stateprovince
        columns:
          - name: stateprovinceid
            description: "Identificador de província"
            tests:
              - not_null
          - name: name
            description: "Nome da proviícia"
            tests:
              - not_null
          - name: territoryid
            description: "Identificador de território"
            tests:
              - not_null
          - name: modifieddate
            description: "Data da última modificação do registro"
            tests:
              - not_null
      - name: address
        columns:
          - name: addressid
            description: "Identificador de endereço"
            tests:
              - unique
              - not_null
          - name: city
            description: "Nome da cidade"
            tests:
              - not_null
          - name: stateprovinceid
            description: "Identificador de província"
            tests:
              - not_null
          - name: spatiallocation
            description: "Localização"
            tests:
              - not_null
      - name: salesorderheadersalesreason
        description: "Tabela de conexão de motivos de venda aos identificadores de venda"
        columns:
          - name: salesorderid
            description: "Identificador de pedido de venda"
            tests:
              - not_null
              - relationships:
                  to: source('raw_adventure_works', 'salesorderheader')
                  field: salesorderid
