version: 2

sources:
  - name: raw_adventure_works
    database: fea24_11
    schema: raw_adventure_works
    tables:
      - name: salesorderheader
      - name: customer
      - name: specialoffer
      - name: salesreason
      - name: creditcard
      - name: product
      - name: productcosthistory
      - name: salesterritory
      - name: salesorderdetail
      - name: stateprovince
      - name: address
